version: '3.8'
services:
  nest-app:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
    ports:
      - "80:3000"
    restart: always
    volumes:
      - /volume/.env:/path/inside/container