name: Deploy to ECR

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build, tag, and push image to Amazon ECR
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # Step 3: Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Step 4: Build, tag, and push image to Amazon ECR
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: react-bapull
          IMAGE_TAG: latest
        run: |
          docker build -t react-bapull .
          docker tag react-bapull:latest 942414443589.dkr.ecr.ap-northeast-2.amazonaws.com/react-bapull:latest
          docker push 942414443589.dkr.ecr.ap-northeast-2.amazonaws.com/react-bapull:latest
