name: Deploy to Amazon ECR and EC2 using CodeDeploy

on:
  push:
    branches:
      - '*'  # 모든 브랜치에 대해 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Create deployment package
      run: |
        mkdir -p deploy_package
        cp appspec.yml deploy_package/
        cp docker-compose.yml deploy_package/
        mkdir -p deploy_package/scripts
        cp scripts/* deploy_package/scripts/
        cd deploy_package && zip -r ../deploy_package.zip .

    - name: Deploy to AWS CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name YourCodeDeployApplicationName \
          --deployment-group-name YourDeploymentGroupName \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --s3-location bucket=${{ secrets.S3_BUCKET }},bundleType=zip,key=deploy_package.zip \
          --file-exists-behavior OVERWRITE