name: Deploy NestJS Docker App to AWS EC2

on:
  push:
    branches:
      - '*'  # 모든 브랜치에 대해 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker build -t hwangjungseok/nestjs-bapull:latest .
          docker push hwangjungseok/nestjs-bapull:latest

      - name: Deploy to EC2
        env:
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ec2-user
        run: |
          echo "$EC2_SSH_PRIVATE_KEY" > private_key
          chmod 400 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${EC2_USER}@${EC2_HOST} '
            docker pull hwangjungseok/nestjs-bapull:latest
            docker stop nest-app || true
            docker rm nest-app || true
            docker run -d --name nest-app -p 3000:3000 hwangjungseok/nestjs-bapull:latest
          '